name: flutter_todo
description: Flutter Todo App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  english_words: ^3.1.5
  http: ^0.12.2
  flutter_svg: ^0.19.2+1
  google_fonts: ^1.1.1
#  dio: ^3.0.10


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/ui/



